# Numpy 

## numpy stands for numeric python and it is the core library for numeric and scientific computing

## it consists of multi- dimensional array object and collection of routine for processing those array

## import the library in your applications by adding the import keyboard and use alias np:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print(np.__version__)

1.24.3


## single dimensional array

In [3]:
l1 = [1,2,3,4,5,6,7,8,9]
type(l1)

list

In [4]:
import numpy as np
n1 =  np.array(l1)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(n1)

numpy.ndarray

## multi-dimensional array

In [6]:
import numpy as np
n2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(n2)

numpy.ndarray

In [8]:
import numpy as np
n3 = np.array([[1,2,3],[4,5]])
n3

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
#np.zeros((no.of rows,no.of coluns))
import numpy as np
n4 = np.zeros((1,2))
n4

array([[0., 0.]])

In [10]:
# np.oned((no.of rows,no. of columns))
import numpy as np
n5 = np.ones((3,5))
n5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# initialize numpy with same number

In [11]:
import numpy as np
n6 = np.full((2,2),10)
n6

array([[10, 10],
       [10, 10]])

In [12]:
import numpy as np
n7 = np.full((5,9),125)
n7

array([[125, 125, 125, 125, 125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125, 125, 125, 125, 125]])

# initialize numpy with range 

In [13]:
import numpy as np
n8 = np.arange(1,20)
n8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
#np.arange(lower limit,upper limit,increment value(by default 1))
import numpy as np
n9 = np.arange(1,20,3)
n9

array([ 1,  4,  7, 10, 13, 16, 19])

# random number generator with numpy array

In [15]:
#np.random.randint(lower limit, upper limit, number of elements in array)
import numpy as np
n10 = np.random.randint(1,100,10)
n10

array([78, 99, 48, 50, 55, 84, 84, 32, 12, 73])

In [16]:
import numpy as np
n11= np.random.randint(1,10,2)
n11

array([4, 5])

# checking size and shape of random array

In [17]:
import numpy as np
n12 = np.random.randint(100,10000,15)
np.size(n12)

15

In [18]:
np.shape(n12)

(15,)

In [19]:
import numpy as np
n13 = np.full((5,9),125)
np.size(n13)

45

In [20]:
np.shape(n13)

(5, 9)

# reshaping the array

In [21]:
import numpy as np
n14 = np.array([[1,2,3,4],[4,5,6,7]])
n14.shape

(2, 4)

In [22]:
n14.shape=(1,8)
n14

array([[1, 2, 3, 4, 4, 5, 6, 7]])

In [23]:
n14.shape = (8,1)
n14

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6],
       [7]])

# Addition of array

In [24]:
import numpy as np
n15 = np.array([10,20])
n16 = np.array([20,30])
num = n15+n16
num

array([30, 50])

In [25]:
num = np.sum([n15,n16])
num

80

In [26]:
n17 = np.random.randint(1,1000,10)
n18 = np.random.randint(1,1000,10)
add=np.sum([n17,n18])
add

10723

In [27]:
nn = np.ones((5,6))
nn1 = np.full((5,6),57)
add = np.sum([nn,nn1])
add

1740.0

# mahtematical operation on array


In [28]:
import numpy as np
nn1= np.array([20,10])
nn2= np.array([10,30])
mul = np.multiply(nn1,nn2)
mul

array([200, 300])

In [29]:
nn3 = np.array([[1,12,14],[14,12,1]])
nn4 = np.array([[1,12,14],[15,14,13]])
into = np.multiply(nn3,nn4)
into

array([[  1, 144, 196],
       [210, 168,  13]])

# Addition of array in colomn and row vise

## addition of column

In [30]:
import numpy as np
n1 = np.array([10,20])
n2 = np.array([10,20])
np.sum([n1,n2], axis=0)

array([20, 40])

## addition of rows

In [31]:
import numpy as np
n1 = np.array([10,20])
n2 = np.array([10,20])
np.sum([n1,n2], axis=1)

array([30, 30])

In [32]:
##basic addition on array
import numpy as np
n3 = np.random.randint(1,10000,25)
n3=n3+10
n3

array([9094, 9144, 2758, 2448, 6408, 5822, 8583, 4568, 1816, 8751, 4724,
       8918, 2978, 9582, 6569, 9313, 2401, 8829, 6425, 2939, 8322, 3887,
       8161, 2710, 4269])

In [33]:
import numpy as np
n4 = np.array([[15,25,222,24,26],[15,12,14,16,17],[15,122,1457,158,1569]])
n4 = n4+100
n4

array([[ 115,  125,  322,  124,  126],
       [ 115,  112,  114,  116,  117],
       [ 115,  222, 1557,  258, 1669]])

In [34]:
import numpy as np
n5 = np.array([[14,25,26,36],[14,6,5,58]])
n5 = n5/5
n5

array([[ 2.8,  5. ,  5.2,  7.2],
       [ 2.8,  1.2,  1. , 11.6]])

In [35]:
import numpy as np
n7 = np.array([[15,14,13,12,11],[10,9,8,7,6],[5,4,3,2,1]])
n7 = n7-15
n7

array([[  0,  -1,  -2,  -3,  -4],
       [ -5,  -6,  -7,  -8,  -9],
       [-10, -11, -12, -13, -14]])

# joining numpy array 

## vstack(): it stack data vertically, it stacks one array vertically on another way

In [36]:
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
n3 = np.vstack((n1,n2))
n3

array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
import numpy as np
n1 = np.array([[10,20,30],
              [70,80,90]])
n2 = np.array([[40,50,60],[25,35,45]])
n3 = np.hstack((n1,n2))
n3

array([[10, 20, 30, 40, 50, 60],
       [70, 80, 90, 25, 35, 45]])

In [38]:
import numpy as np
n1 = np.array([10,20,30,70,80,90])
n2 = np.array([40,50,60,25,35,45])
n3 =np.column_stack((n1,n2))
n3

array([[10, 40],
       [20, 50],
       [30, 60],
       [70, 25],
       [80, 35],
       [90, 45]])

## numpy intersaction and difference

## intersect1d():- it's a method used to find similar elements in array

In [39]:
import numpy as np
n1 = np.array([10,20,30,40,50,60,70,80,90])
n2 = np.array([10,20,40,30,60,45,55,65,75,85,95])
n3 = np.intersect1d(n1,n2)
n3

array([10, 20, 30, 40, 60])

In [40]:
import numpy as np
n1 = np.array([[10,20,30],[25,50,54],[45,48,49]])
n2 = np.array([[15,25,35],[10,20,30],[45,45,45]])
n3 = np.intersect1d(n1,n2)
n3

array([10, 20, 25, 30, 45])

## setdiff1d():- its to seperate unique value in first array n1, in resultant array remove common element in both array and unique in n2 array

In [41]:
import numpy as np
n1 = np.array([[10,20,30,40,50],[20,40,60,80,100]])
n2 = np.array([[30,40,50,60,70],[80,90,100,110,120]])
n3 = np.setdiff1d(n1,n2)
n3

array([10, 20])

In [42]:
import numpy as np
n1 = np.array([[10,20,30,40,50],[20,40,60,80,100]])
n2 = np.array([[30,40,50,60,70],[80,90,100,110,120]])
n3 = np.setdiff1d(n2,n1)
n3

array([ 70,  90, 110, 120])

# Numpy math function

# mean function

In [43]:
import numpy as np
n1 = np.array([10,20,30,50,60,80,90,73,25,55,65,85,45,75,85,95,65,35,25,15,45])
np.mean(n1)

53.714285714285715

In [44]:
import numpy as np
n1 = np.array([[10,20,30,100],[50,60,80,200],[90,73,25,300],[55,65,85,400],[45,75,85,500],[95,65,35,600],[25,15,45,700]])
np.mean(n1)

140.28571428571428

## median function

In [45]:
import numpy as np
n1 = np.array([20,25,65,85,95,75,45,11,22,33,55,66,88,99,77,44,55,88,56,55,85,95,65,26,5,5,56,56,456,56,56,5,65,6])
np.median(n1)

56.0

## standard deviation

In [46]:
import numpy as np
n1 = np.array([12,23,34,45,56,67,78,89,91,12,23,34,45,56,67,78,89])
np.std(n1)

26.24294269937141

In [47]:
import numpy as np
n1 = np.array([[12,23,34],[45,56,67],[78,89,91]])
np.std(n1)

26.956755492207638

In [48]:
## numpy file save and load

In [49]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.save('My_first_numpy',n1)

In [50]:
n2 = np.load('My_first_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])

## python program to demonstrate the use of numpy arrays

In [51]:
import numpy as np

list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,15,16,17,18,19,20]

n1 = np.array(list1)
n2 = np.array(list2)

print('Result array is:-', n1+n2)

Result array is:- [12 14 16 18 20 22 24 26 28 30]


In [52]:
import numpy as np

tup1 = (1,2,3,4,5,6,7,8,9,10)
tup2 = (21,22,23,24,25,26,27,28,29,30)

n1 = np.array(tup1)
n2 = np.array(tup2)

print('rusult of array is:-',n1+n2)

rusult of array is:- [22 24 26 28 30 32 34 36 38 40]


In [53]:
import numpy as np
#creating a sequence of integer from 20 to 1 wiht a step of -4
n1= np.arange(20,1,-3)
print('a sequence array with a negetive step:- ',n1)

n2 = n1[np.array([3,5,2])]
print('element at these indices are:- ',n2)

a sequence array with a negetive step:-  [20 17 14 11  8  5  2]
element at these indices are:-  [11  5 14]


# indexing using index array

In [54]:
import numpy as np
# numpy array with element fron 11 to 19
n1 = np.array([11,12,13,4,15,16,17,18,19,20])

#indexing values can be negative
n2 = n1[np.array([1,2,-3])]
print('element are: - ',n2)

element are: -  [12 13 18]


# python program for basic slicing

In [55]:
import numpy as np

n1 = np.arange(20)
print('Array is:-',n1)

print(' n1[-8:17:1] :)',n1[-8:17:1])

print('n1[10:]=',n1[10:])

Array is:- [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 n1[-8:17:1] :) [12 13 14 15 16]
n1[10:]= [10 11 12 13 14 15 16 17 18 19]
